services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    image: speak_ai_backend:cpu 
    container_name: speak_ai_backend_cpu
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:9000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
    networks:
      - kokoro_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  tts_kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: tts_kokoro
    ports:
      - "0.0.0.0:8880:8880"
    networks:
      - kokoro_network
    restart: unless-stopped

networks:
  kokoro_network:
    name: kokoro_network
    driver: bridge
    